### ISSUE TITLE
Problema addReplyTo

### ISSUE THREAD

**Issue by cvsolutions** [vikey89/EmailZF2#1]
Ciao Vincenzo, ho visto che il  metodo addReplyTo() NON risulta personalizzabile.
Secondo me potresti impostarlo per default così per come è fatto ($mail->addReplyTo($this->_from_mail, $this->_from_name);) ma allo stesso tempo dare la possibilità di settarlo nell'array() del metodo send().

**Comment by vikey89** [comment]
Ciao Concetto, si il metodo addReplyTo non è personalizzabile al momento. Appena ho 2 minuti sistemo questa cosa. 
Se è una cosa urgente ti aggiungo come collaboratore cosi puoi fare direttamente tu la modifica.
Fammi sapere.
